name: Build macOS App
 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. הורדת הקוד מהמאגר
    - uses: actions/checkout@v3

    # 2. התקנת Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    # 3. התקנת PyInstaller (הכלי שמקמפל)
    - name: Install Dependencies
      run: |
        pip install pyinstaller
        pip install tk  # בדרך כלל מובנה, אבל ליתר ביטחון

    # 4. ביצוע הקמפול (החלק החשוב)
    # --onefile: קובץ אחד
    # --windowed: ללא חלון שחור (קונסול) מאחורה
    # --icon: האייקון שלך
    - name: Build with PyInstaller
      run: |
        pyinstaller --clean --onefile --windowed --icon=2.icns --name="NetGuard" Install_Net_Block.py

    # 5. העלאת הקובץ המוכן (Artifact) כדי שתוכל להוריד אותו
    - name: Upload App
      uses: actions/upload-artifact@v4
      with:
        name: NetGuard-App
        path: dist/NetGuard.app
